apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "get-cloudflare-logs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "get-cloudflare-logs.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "get-cloudflare-logs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "get-cloudflare-logs.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "get-cloudflare-logs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CF_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "get-cloudflare-logs.fullname" . }}
                  key: CF_ZONE_ID
            - name: CF_AUTH_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "get-cloudflare-logs.fullname" . }}
                  key: CF_AUTH_EMAIL
            - name: CF_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "get-cloudflare-logs.fullname" . }}
                  key: CF_AUTH_KEY
            - name: SAMPLE_RATE
              value: {{ .Values.config.cloudflare.sampleRate | quote }}
            - name: ES_HOST
              value: {{ .Values.config.elasticsearch.host | quote }}
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "get-cloudflare-logs.fullname" . }}
                  key: ES_USERNAME
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "get-cloudflare-logs.fullname" . }}
                  key: ES_PASSWORD
            - name: ES_INDEX
              value: {{ .Values.config.elasticsearch.index.name | quote }}
            - name: ES_TEMPLATE_ENABLED
              value: {{ default "false" .Values.config.elasticsearch.index.template.enabled | quote }}
            - name: ES_TEMPLATE_INDEX_SHARDS
              value: {{ .Values.config.elasticsearch.index.template.shards | quote }}
            - name: ES_TEMPLATE_INDEX_REPLICAS
              value: {{ .Values.config.elasticsearch.index.template.replicas | quote }}
            - name: ES_TEMPLATE_INDEX_REFRESH
              value: {{ .Values.config.elasticsearch.index.template.refreshInterval | quote }}
            - name: ES_PIPELINE_ENABLED
              value: {{ default "false" .Values.config.elasticsearch.pipeline.enabled | quote }}
            - name: ES_PIPELINE_DEFAULT_ENABLED
              value: {{ default "false" .Values.config.elasticsearch.pipeline.default | quote }}
            - name: ES_ILM_ENABLED
              value: {{ .Values.config.elasticsearch.ilm.enabled | quote }}
            {{- if .Values.config.elasticsearch.ilm.enabled }}
            - name: ES_ILM_DEFAULT_POLICY_ENABLED
              value: "false"
            - name: ES_ILM_POLICY_FILE
              value: "/opt/filebeat/ilm-policy.json"
            {{- end }}
          {{- if .Values.config.elasticsearch.ilm.enabled }}
          volumeMounts:
            - name: ilm-policy
              mountPath: /opt/filebeat
              subPath: ilm-policy.json
              readOnly: true
          {{- end }}
          livenessProbe:
            exec:
              command:
              - pgrep
              - filebeat
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - pgrep
              - filebeat
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.config.elasticsearch.ilm.enabled }}
      volumes:
        - name: ilm-policy
          configMap:
            name: {{ .Release.Name }}-ilm-policy
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
