apiVersion: v1
kind: Secret
metadata:
  name: {{ include "get-cloudflare-logs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "get-cloudflare-logs.labels" . | nindent 4 }}
type: Opaque
data:
  CF_ZONE_ID: {{ .Values.config.cloudflare.zoneId | b64enc }}
  CF_AUTH_EMAIL: {{ .Values.config.cloudflare.authEmail | b64enc }}
  CF_AUTH_KEY: {{ .Values.config.cloudflare.authKey | b64enc }}
  {{- if .Values.config.elasticsearch.username }}
  ES_USERNAME: {{ .Values.config.elasticsearch.username | b64enc }}
  {{- end -}}
  {{ if .Values.config.elasticsearch.password }}
  ES_PASSWORD: {{ .Values.config.elasticsearch.password | b64enc }}
  {{ end -}}

