# Default values for get-cloudflare-logs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# application config
config:

  cloudflare:
    zoneId: "51e241f08e014feb95d1b2760228d12a"
    authEmail: "admin@example.com"
    authKey: "51e241f08e014feb95d1b2760228d12a2df50"
    sampleRate: "0.01" # sample percent of logs, 0.01 = 1%


  elasticsearch:
    host: "http://elasticsearch:9200"  # make sure to always include port!
    username: ~  # for password protected Elasticsearch instances
    password: ~  # set username and password

    index:
      name: "cloudflare-access"
      template:
        enabled: true            # enables template setup
        shards: "5"              # sets number of index shards
        replicas: "0"            # sets number of index replicas
        refreshInterval: "10s"   # sets index refresh interval

    # ingest pipeline is using processors to extract helpful info, and more
    pipeline:
      enabled: true  # enables pipeline (unless true, UserAgent, and Lat/Lon
                     # will not be available)
      default: true  # enables use of default pipeline, customization is not
                     # supported at the moment, and it's unlikely you'll want to
                     # change it anyways
      # default pipeline is configured with following processors:
      # user_agent - to process cloudflare.ClientRequestUserAgent
      # geoip - to process cloudflare.ClientIP

    ilm:
      # When ILM is enabled, and ilm.default is set to "true"
      #   default policy from the image will be used
      # Custom ILM policy can be used by setting ilm.default to "false"
      #   and specifying policyFile location as local filepath of JSON file.
      # See example ILM policy in ./files/ilm-default-policy.json
      # To learn more about Elasticsearch ILM see Elasticsearch docs
      #   https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html
      enabled: true  # enables setup of ilm on start

      # ILM policy can be defined via either of these,
      # listed in the order of priority
      # - policyYAML
      # - policyJSON
      # - policyFile
      #
      # all default policies are identical

      # takes precedence
      policyYAML:
        phases:
          hot:
            min_age: 0ms
            actions:
              rollover:
                max_size: 60gb
                max_age: 1d
          warm:
            min_age: 0ms
            actions:
              forcemerge:
                max_num_segments: 1
          delete:
            min_age: 7d
            actions:
              delete: {}

      # used if policyYAML is unset, empty or nil
      policyJSON: |
        {
          "policy": {
            "phases": {
              "hot": {
                "min_age": "0ms",
                "actions": {
                  "rollover": {
                    "max_size": "60gb",
                    "max_age": "1d"
                  }
                }
              },
              "warm": {
                "min_age": "0ms",
                "actions": {
                  "forcemerge": {
                    "max_num_segments" : 1
                  }
                }
              },
              "delete": {
                "min_age": "7d",
                "actions": {
                  "delete": { }
                }
              }
            }
          }
        }

      # used if both policyYAML and policyJSON are unset, empty or nil
      policyFile: "files/ilm-default-policy.json"


# k8s objects config
terminationGracePeriodSeconds: 15
revisionHistoryLimit: 10

image:
  repository: docker.io/anapsix/get-cloudflare-logs
  tag: ~  # if unset or null, {{ .Chart.AppVersion }} will be used
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
